import 'package:flutter/material.dart';

class LocalizationService {
  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'app_title': 'SisaPintar',
      'home': 'Beranda',
      'recipe': 'Resep',
      'tracker': 'Tracker',
      'dashboard': 'Dashboard',
      'settings': 'Pengaturan',
      
      // Home Screen
      'welcome': 'Selamat datang, Mohammed! 👋',
      'critical_alert': '⚠️ Kamu punya {count} bahan yang hampir kedaluwarsa!',
      'all_safe': '✅ Semua bahan makananmu aman! 🌿',
      'eco_impact': 'Dampak Eco-mu Minggu Ini',
      'food_saved': 'makanan diselamatkan',
      'money_saved': 'dihemat',
      'recipes_cooked': 'resep dimasak',
      'expiring_soon_title': 'Bahan Segera Kedaluwarsa',
      'view_all': 'Lihat semua →',
      'quick_recipe_ai': 'Cari Resep AI',
      'quick_recipe_desc': 'Dari sisa bahanmu',
      'quick_tracker_desc_critical': '{count} bahan kritis!',
      'quick_tracker_desc_safe': '{count} bahan aman',
      'today_tips': 'Tips Hari Ini',
      'days_left': '{count} hari lagi',
      
      // Recipe Screen
      'recipe_ai_title': 'Smart Recipe AI ✦',
      'recipe_ai_subtitle': 'Pilih bahan, biarkan AI memasak untukmu!',
      'choose_ingredients': '🥗 Pilih Bahan Kulkas:',
      'choose_critical': 'Pilih {count} kritis',
      'no_ingredients_tracker': 'Belum ada bahan di tracker.\nTambah dulu di tab Tracker!',
      'add_more': 'Tambahan:',
      'add_custom_hint': 'Tambahkan bahan lain...',
      'ingredients_selected': '{count} bahan dipilih',
      'clear_all': 'Hapus semua',
      'search_recipe_btn': 'Cari Resep AI ✦',
      'ai_analyzing': 'AI sedang menganalisis bahan...',
      'ai_recommendation': 'Rekomendasi Resep AI 🍽️',
      'recipe_copied': '📋 Resep disalin!',
      'recipe_shared': '📤 Resep siap dibagikan! (disalin ke clipboard)',
      'cancel': 'Cancel',
      'finish_cooking': 'Selesai Memasak! 🍳',
      'saved_recipes_title': 'Resep Tersimpan',
      'recipes_count': '{count} resep',
      'tap_to_view': 'Ketuk untuk lihat resep',
      'just_saved': '✅ Resep Tersimpan!',
      'save_recipe': '💾 Simpan Resep',
      'cooking_done_snack': 'Masakan selesai! {count} bahan dikonsumsi & diselamatkan (Rp {money})!',
      'cooking_done_custom_snack': 'Masakan selesai! Bahan tambahan dikonsumsi. 🌿',
      'select_at_least_one': 'Pilih minimal 1 bahan sisa kulkas Anda!',

      // Tracker Screen
      'tracker_title': '🥦 Expiry Tracker',
      'add_ingredient': 'Tambah Bahan',
      'filter_all': 'Semua ({count})',
      'filter_critical': 'Kritis ⚠️ ({count})',
      'filter_soon': 'Segera 🟡 ({count})',
      'filter_safe': 'Aman ✅',
      'critical_banner': '⚠️ {count} bahan kritis!',
      'critical_banner_desc': 'Segera masak untuk kurangi food waste.',
      'add_food_title': '➕ Tambah Bahan Makanan',
      'edit_food_title': '✏️ Edit Bahan Makanan',
      'choose_icon': 'Pilih Ikon:',
      'food_name_label': 'Nama Bahan *',
      'category_label': 'Kategori (misal: Sayuran)',
      'days_before_expiry': 'Hari Sebelum Kedaluwarsa *',
      'weight_label': 'Berat (kg)',
      'price_label': 'Harga (Rp)',
      'save_btn': 'Simpan Bahan',
      'save_changes_btn': 'Simpan Perubahan',
      'delete_btn': 'Hapus Bahan',
      'confirm_delete_title': 'Hapus Bahan?',
      'confirm_delete_desc': 'Yakin ingin menghapus {name}?',
      'confirm_delete_desc_no_history': 'Yakin ingin menghapus {name} tanpa riwayat?',
      'added_success': '✅ {name} berhasil ditambahkan!',
      'updated_success': '✅ {name} berhasil diperbarui!',
      'deleted_msg': '🗑️ {name} dihapus',
      'empty_tracker_title': 'Belum ada bahan makanan',
      'empty_tracker_subtitle': 'Tekan tombol + untuk menambahkan\nbahan makanan pertama Anda 🌿',
      'empty_filter_title': 'Tidak ada bahan di kategori ini',
      
      // Dashboard Screen
      'dashboard_title': 'Eco-Impact Dashboard',
      'eco_level': 'Level: Eco Warrior 🌿',
      'saved_desc': 'makanan berhasil diselamatkan',
      'next_level': 'Level selanjutnya: 15 kg (Kurang {kg} kg)',
      'total_saved_money': 'Total dihemat',
      'cooked_count': 'Berhasil dimasak',
      'composition_title': 'Komposisi Pengelolaan Bahan (%)',
      'saved': 'Diselamatkan',
      'wasted': 'Terbuang',
      'weekly_progress': 'Progress Penyelamatan Mingguan',
      'achievements': 'Pencapaianmu 🏅',
      'badge_first_save_title': 'First Save',
      'badge_first_save_desc': 'Pertama kali menyelamatkan bahan',
      'badge_chef_title': 'Chef Hemat',
      'badge_chef_desc': 'Masak 5+ resep dari sisa',
      'badge_zero_waste_title': 'Zero Waste Hero',
      'badge_zero_waste_desc': 'Selamatkan 10kg bahan',
      'period_week': 'Minggu Ini',
      'period_month': 'Bulan Ini',
      'period_all': 'Semua Waktu',
      
      // Settings Screen
      'settings_title': 'Pengaturan Umum ⚙️',
      'language_settings': 'Bahasa / Language',
      'dark_mode': 'Mode Gelap',
      'dark_mode_desc': 'Sesuaikan kenyamanan mata Anda',
      'api_key_settings': 'Groq API Key',
      'api_key_desc': '🔑 API Key untuk resep AI pintar',
      'get_api_key_hint': 'Dapatkan key gratis di console.groq.com',
      'api_key_saved': '🔑 API Key berhasil disimpan!',
      'api_key_active': '✅ Aktif',
      'api_key_inactive': '❌ Belum Diatur',
      'clear_db': 'Hapus Semua Data',
      'clear_db_desc': '⚠️ Menghapus semua bahan makanan & riwayat',
      'clear_db_confirm_title': 'Hapus Semua Data?',
      'clear_db_confirm_desc': 'Tindakan ini akan menghapus seluruh data bahan makanan dan riwayat dampak Eco. Tindakan ini tidak bisa dibatalkan.',
      'clear_db_success': '🗑️ Semua data berhasil dihapus!',
      'about_title': 'Tentang SisaPintar',
      'about_desc': 'SisaPintar adalah aplikasi asisten pintar yang dirancang to membantu Anda melacak tanggal kedaluwarsa bahan makanan dan memasaknya menggunakan AI, demi mengurangi pemborosan makanan (SDG 12: Konsumsi & Produksi yang Bertanggung Jawab).',
    },
    'en': {
      'app_title': 'SisaPintar',
      'home': 'Home',
      'recipe': 'Recipe',
      'tracker': 'Tracker',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      
      // Home Screen
      'welcome': 'Welcome, Mohammed! 👋',
      'critical_alert': '⚠️ You have {count} ingredients expiring soon!',
      'all_safe': '✅ All your ingredients are safe! 🌿',
      'eco_impact': 'Your Eco-Impact This Week',
      'food_saved': 'food items saved',
      'money_saved': 'saved',
      'recipes_cooked': 'recipes cooked',
      'expiring_soon_title': 'Expiring Soon',
      'view_all': 'View all →',
      'quick_recipe_ai': 'Smart Recipe AI',
      'quick_recipe_desc': 'Cook from your leftovers',
      'quick_tracker_desc_critical': '{count} critical items!',
      'quick_tracker_desc_safe': '{count} items safe',
      'today_tips': 'Today\'s Tips',
      'days_left': '{count} days left',
      
      // Recipe Screen
      'recipe_ai_title': 'Smart Recipe AI ✦',
      'recipe_ai_subtitle': 'Choose ingredients, let AI cook for you!',
      'choose_ingredients': '🥗 Choose Fridge Ingredients:',
      'choose_critical': 'Select {count} critical',
      'no_ingredients_tracker': 'No ingredients in tracker.\nAdd some in the Tracker tab first!',
      'add_more': 'Extra Ingredients:',
      'add_custom_hint': 'Add other ingredients...',
      'ingredients_selected': '{count} ingredients selected',
      'clear_all': 'Clear all',
      'search_recipe_btn': 'Search Recipe AI ✦',
      'ai_analyzing': 'AI is analyzing ingredients...',
      'ai_recommendation': 'AI Recipe Recommendation 🍽️',
      'recipe_copied': '📋 Recipe copied!',
      'recipe_shared': '📤 Recipe ready to share! (copied to clipboard)',
      'cancel': 'Cancel',
      'finish_cooking': 'Finish Cooking! 🍳',
      'saved_recipes_title': 'Saved Recipes',
      'recipes_count': '{count} recipes',
      'tap_to_view': 'Tap to view recipe',
      'just_saved': '✅ Recipe Saved!',
      'save_recipe': '💾 Save Recipe',
      'cooking_done_snack': 'Cooking completed! {count} ingredients consumed & saved (Rp {money})!',
      'cooking_done_custom_snack': 'Cooking completed! Extra ingredients consumed. 🌿',
      'select_at_least_one': 'Select at least 1 fridge ingredient!',

      // Tracker Screen
      'tracker_title': '🥦 Expiry Tracker',
      'add_ingredient': 'Add Ingredient',
      'filter_all': 'All ({count})',
      'filter_critical': 'Critical ⚠️ ({count})',
      'filter_soon': 'Soon 🟡 ({count})',
      'filter_safe': 'Safe ✅',
      'critical_banner': '⚠️ {count} ingredients critical!',
      'critical_banner_desc': 'Cook soon to reduce food waste.',
      'add_food_title': '➕ Add Food Item',
      'edit_food_title': '✏️ Edit Food Item',
      'choose_icon': 'Choose Icon:',
      'food_name_label': 'Ingredient Name *',
      'category_label': 'Category (e.g., Vegetable)',
      'days_before_expiry': 'Days Before Expiry *',
      'weight_label': 'Weight (kg)',
      'price_label': 'Price (Rp)',
      'save_btn': 'Save Ingredient',
      'save_changes_btn': 'Save Changes',
      'delete_btn': 'Delete Ingredient',
      'confirm_delete_title': 'Delete Ingredient?',
      'confirm_delete_desc': 'Are you sure you want to delete {name}?',
      'confirm_delete_desc_no_history': 'Are you sure you want to delete {name} without history?',
      'added_success': '✅ {name} successfully added!',
      'updated_success': '✅ {name} successfully updated!',
      'deleted_msg': '🗑️ {name} deleted',
      'empty_tracker_title': 'No food items yet',
      'empty_tracker_subtitle': 'Press the + button to add\nyour first food item 🌿',
      'empty_filter_title': 'No items in this category',
      
      // Dashboard Screen
      'dashboard_title': 'Eco-Impact Dashboard',
      'eco_level': 'Level: Eco Warrior 🌿',
      'saved_desc': 'food items successfully saved',
      'next_level': 'Next Level: 15 kg ({kg} kg left)',
      'total_saved_money': 'Total saved',
      'cooked_count': 'Successfully cooked',
      'composition_title': 'Food Waste Composition (%)',
      'saved': 'Saved',
      'wasted': 'Wasted',
      'weekly_progress': 'Weekly Saving Progress',
      'achievements': 'Your Achievements 🏅',
      'badge_first_save_title': 'First Save',
      'badge_first_save_desc': 'Saved food for the first time',
      'badge_chef_title': 'Smart Chef',
      'badge_chef_desc': 'Cooked 5+ recipes from leftovers',
      'badge_zero_waste_title': 'Zero Waste Hero',
      'badge_zero_waste_desc': 'Saved 10kg of food items',
      'period_week': 'This Week',
      'period_month': 'This Month',
      'period_all': 'All Time',
      
      // Settings Screen
      'settings_title': 'General Settings ⚙️',
      'language_settings': 'Language / Bahasa',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Adjust for eye comfort',
      'api_key_settings': 'Groq API Key',
      'api_key_desc': '🔑 API Key for smart AI recipes',
      'get_api_key_hint': 'Get a free key at console.groq.com',
      'api_key_saved': '🔑 API Key saved successfully!',
      'api_key_active': '✅ Active',
      'api_key_inactive': '❌ Not Set',
      'clear_db': 'Reset All Data',
      'clear_db_desc': '⚠️ Deletes all food items & history',
      'clear_db_confirm_title': 'Reset All Data?',
      'clear_db_confirm_desc': 'This action will delete all food items and your Eco-impact history. This cannot be undone.',
      'clear_db_success': '🗑️ All data successfully cleared!',
      'about_title': 'About SisaPintar',
      'about_desc': 'SisaPintar is a smart assistant designed to help you track expiry dates of food items and cook recipes using AI, to reduce food waste (SDG 12: Responsible Consumption and Production).',
    },
    'ar': {
      'app_title': 'حصادنا الذكي',
      'home': 'الرئيسية',
      'recipe': 'وصفات AI',
      'tracker': 'المتتبع',
      'dashboard': 'الإحصائيات',
      'settings': 'الإعدادات',
      
      // Home Screen
      'welcome': 'مرحباً بك، محمد! 👋',
      'critical_alert': '⚠️ لديك {count} من المكونات شارفت صلاحيتها على الانتهاء!',
      'all_safe': '✅ جميع مكوناتك الغذائية في أمان! 🌿',
      'eco_impact': 'تأثيرك البيئي هذا الأسبوع',
      'food_saved': 'وجبة تم إنقاذها',
      'money_saved': 'مبلغ تم توفيره',
      'recipes_cooked': 'وصفة تم طبخها',
      'expiring_soon_title': 'مواد توشك على الانتهاء',
      'view_all': 'عرض الكل ←',
      'quick_recipe_ai': 'وصفات AI الذكية',
      'quick_recipe_desc': 'اطبخ من بقايا طعامك',
      'quick_tracker_desc_critical': '{count} مواد حرجة!',
      'quick_tracker_desc_safe': '{count} مواد آمنة',
      'today_tips': 'نصيحة اليوم',
      'days_left': 'متبقي {count} أيام',
      
      // Recipe Screen
      'recipe_ai_title': 'وصفات الذكاء الاصطناعي ✦',
      'recipe_ai_subtitle': 'اختر المكونات، ودع الذكاء الاصطناعي يطبخ لك!',
      'choose_ingredients': '🥗 اختر مكونات الثلاجة:',
      'choose_critical': 'اختر {count} حرجة',
      'no_ingredients_tracker': 'لا توجد مكونات في المتتبع بعد.\nأضف بعضها أولاً من تبويب المتتبع!',
      'add_more': 'مكونات إضافية:',
      'add_custom_hint': 'أضف مكونات أخرى...',
      'ingredients_selected': 'تم اختيار {count} مكونات',
      'clear_all': 'حذف الكل',
      'search_recipe_btn': 'بحث عن وصفة بالذكاء الاصطناعي ✦',
      'ai_analyzing': 'الذكاء الاصطناعي يحلل المكونات...',
      'ai_recommendation': 'توصية وصفة الذكاء الاصطناعي 🍽️',
      'recipe_copied': '📋 تم نسخ الوصفة!',
      'recipe_shared': '📤 الوصفة جاهزة للمشاركة! (تم النسخ للحافظة)',
      'cancel': 'كنسل',
      'finish_cooking': 'اكتمل الطبخ! 🍳',
      'saved_recipes_title': 'الوصفات المحفوظة',
      'recipes_count': '{count} وصفة',
      'tap_to_view': 'اضغط لعرض الوصفة',
      'just_saved': '✅ تم حفظ الوصفة!',
      'save_recipe': '💾 حفظ الوصفة',
      'cooking_done_snack': 'اكتمل الطبخ! تم استهلاك وإنقاذ {count} مكونات (توفير {money} روبية)!',
      'cooking_done_custom_snack': 'اكتمل الطبخ! تم استهلاك المكونات الإضافية. 🌿',
      'select_at_least_one': 'اختر مكوناً واحداً على الأقل من الثلاجة!',

      // Tracker Screen
      'tracker_title': '🥦 متتبع الصلاحية',
      'add_ingredient': 'إضافة مكون',
      'filter_all': 'الكل ({count})',
      'filter_critical': 'حرجة ⚠️ ({count})',
      'filter_soon': 'قريباً 🟡 ({count})',
      'filter_safe': 'آمنة ✅',
      'critical_banner': '⚠️ {count} مكونات في حالة حرجة!',
      'critical_banner_desc': 'اطبخها سريعاً للحد من هدر الطعام.',
      'add_food_title': '➕ إضافة مادة غذائية',
      'edit_food_title': '✏️ تعديل مادة غذائية',
      'choose_icon': 'اختر الأيقونة:',
      'food_name_label': 'اسم المكون *',
      'category_label': 'الفئة (مثال: خضروات)',
      'days_before_expiry': 'أيام قبل انتهاء الصلاحية *',
      'weight_label': 'الوزن (كجم)',
      'price_label': 'السعر (روبية)',
      'save_btn': 'حفظ المكون',
      'save_changes_btn': 'حفظ التعديلات',
      'delete_btn': 'حذف المكون',
      'confirm_delete_title': 'حذف المكون؟',
      'confirm_delete_desc': 'هل أنت متأكد من حذف {name}؟',
      'confirm_delete_desc_no_history': 'هل أنت متأكد من حذف {name} دون تسجيل في السجل؟',
      'added_success': '✅ تم إضافة {name} بنجاح!',
      'updated_success': '✅ تم تعديل {name} بنجاح!',
      'deleted_msg': '🗑️ تم حذف {name}',
      'empty_tracker_title': 'لا توجد أطعمة مضافة بعد',
      'empty_tracker_subtitle': 'اضغط على زر + لإضافة\nأول مادة غذائية وتتبع صلاحيتها 🌿',
      'empty_filter_title': 'لا توجد أطعمة في هذه الفئة',
      
      // Dashboard Screen
      'dashboard_title': 'لوحة التأثير البيئي',
      'eco_level': 'المستوى: محارب الهدر 🌿',
      'saved_desc': 'من الأطعمة تم إنقاذها بنجاح',
      'next_level': 'المستوى القادم: 15 كجم (تبقي {kg} كجم)',
      'total_saved_money': 'إجمالي التوفير',
      'cooked_count': 'تم طبخها بنجاح',
      'composition_title': 'مصير إدارة الطعام (%)',
      'saved': 'تم إنقاذه',
      'wasted': 'تم هدره',
      'weekly_progress': 'تقدم إنقاذ الطعام الأسبوعي',
      'achievements': 'إنجازاتك 🏅',
      'badge_first_save_title': 'البداية الخضراء',
      'badge_first_save_desc': 'أنقذت الطعام لأول مرة',
      'badge_chef_title': 'طباخ ذكي',
      'badge_chef_desc': 'طبخت 5+ وصفات من بقايا الأطعمة',
      'badge_zero_waste_title': 'صديق البيئة',
      'badge_zero_waste_desc': 'أنقذت 10 كجم من الأطعمة',
      'period_week': 'هذا الأسبوع',
      'period_month': 'هذا الشهر',
      'period_all': 'كل الأوقات',
      
      // Settings Screen
      'settings_title': 'الإعدادات العامة ⚙️',
      'language_settings': 'اللغة / Language',
      'dark_mode': 'الوضع الداكن',
      'dark_mode_desc': 'مريح للعينين في البيئات المظلمة',
      'api_key_settings': 'مفتاح API لـ Groq',
      'api_key_desc': '🔑 مفتاح API لوصفات الذكاء الاصطناعي',
      'get_api_key_hint': 'احصل على مفتاح مجاني من console.groq.com',
      'api_key_saved': '🔑 تم حفظ مفتاح API بنجاح!',
      'api_key_active': '✅ نشط',
      'api_key_inactive': '❌ غير معين',
      'clear_db': 'إعادة ضبط البيانات',
      'clear_db_desc': '⚠️ حذف جميع الأطعمة وسجل التأثير',
      'clear_db_confirm_title': 'إعادة ضبط كافة البيانات؟',
      'clear_db_confirm_desc': 'سيؤدي هذا الإجراء إلى حذف جميع الأطعمة المخزنة وسجل التأثير البيئي بالكامل. لا يمكن التراجع عن هذا الإجراء.',
      'clear_db_success': '🗑️ تم مسح جميع البيانات بنجاح!',
      'about_title': 'حول حصادنا الذكي',
      'about_desc': 'حصادنا الذكي (SisaPintar) هو مساعد ذكي لمساعدتك في تتبع تواريخ انتهاء صلاحية الأطعمة وإعداد وصفات شهية باستخدام الذكاء الاصطناعي، بهدف تقليل هدر الطعام تماشياً مع الهدف 12 من أهداف التنمية المستدامة للأمم المتحدة (الاستهلاك والإنتاج المسؤولان).',
    }
  };

  /// Returns translated text for given [key] in [localeCode].
  /// Fallbacks to English ('en') if key or language is missing.
  static String translate(BuildContext context, String key, {Map<String, String>? args}) {
    // Determine the current locale from context or settings
    // In our app, we can read it from the AppSettingsProvider using Provider.of or a global helper
    // Or we can pass it down.
    return key; // We will use a more robust implementation that determines the locale
  }

  static String get(String currentLocale, String key, {Map<String, String>? args}) {
    final Map<String, String> langMap = _localizedValues[currentLocale] ?? _localizedValues['en']!;
    String translation = langMap[key] ?? _localizedValues['en']![key] ?? key;
    
    if (args != null) {
      args.forEach((placeholder, value) {
        translation = translation.replaceAll('{$placeholder}', value);
      });
    }
    
    return translation;
  }
}
